/*
 * The MIT License
 *
 * Copyright (c) 2016-17 Samsung Electronics Co., Ltd. All Rights Reserved
 * For conditions of distribution and use, see the accompanying COPYING file.
 *
 */

//
// Autogenerated by ./src/generate_dcapi_strings.py
//
#ifndef DCAPI_STRINGS_H
#define DCAPI_STRINGS_H

#include <stdint.h>
#include <string.h>
#include "DCAPI.h"

extern const char * DCAPI_RunString(eRun v);
extern const char * DCAPI_CategoryString(eCategory v);
extern const char * DCAPI_TypeString(eType v);
extern const char * DCAPI_UnitString(eUnit v);
extern const char * DCAPI_ErrorString(eError v);
extern const char * DCAPI_EnableString(eEnable v);

extern eRun DCAPI_RunFromString(const char* s);
extern eCategory DCAPI_CategoryFromString(const char* s);
extern eType DCAPI_TypeFromString(const char* s);
extern eUnit DCAPI_UnitFromString(const char* s);
extern eError DCAPI_ErrorFromString(const char* s);
extern eEnable DCAPI_EnableFromString(const char* s);

#endif // header
