// Copyright (C) 2002-2018 Codeplay Software Limited. All Rights Reserved.

/// @file
///
/// @brief Defines the Shader analysis view widget
///
/// @copyright
/// Copyright (C) 2002-2018 Codeplay Software Limited. All Rights Reserved.

#ifndef LPGPU2_PP_SHADERANALYSISVIEW_H_INCLUDE
#define LPGPU2_PP_SHADERANALYSISVIEW_H_INCLUDE

// Qt:
#include <QWidget>

// Infra:
#include <AMDTBaseTools/Include/AMDTDefinitions.h>


namespace lpgpu2 { enum class PPFnStatus; }
class QTableWidget;
class QPushButton;

/// @brief   Defines the Shader Analysis View widget used to display
///          annotations related to shader code as generated by the 
///          feedback engine.
/// @warning This widget is not being populated with data yet.
/// @author  Thales Sabino
/// @date    20/11/2017
// clang-format off
class LPGPU2ppShaderAnalysisView : public QWidget
{
    Q_OBJECT
// Methods:
public:
    explicit LPGPU2ppShaderAnalysisView(QWidget *vpParent, gtUInt32 vFrameNum, gtUInt32 vDrawNum);
    virtual ~LPGPU2ppShaderAnalysisView();

    lpgpu2::PPFnStatus Initialise();
    lpgpu2::PPFnStatus Shutdown();
    
signals:
    void ShaderSourceOpenRequested(gtUInt32 frameNum, gtUInt32 drawNum);

// Methods:
private:
    QTableWidget* m_pCompilerAnalysisTableWidget = nullptr;
    QTableWidget* m_pSuggestionsTableWidget = nullptr;
    QPushButton*  m_pOpenSourceButton = nullptr;
    QWidget*      m_pButtonContainer = nullptr;
    
    gtUInt32      m_frameID;
    gtUInt32      m_drawID;
    
private slots:
    void OnOpenSourceButtonClicked();
};
// clang-format on

#endif // LPGPU2_PP_SHADERANALYSISVIEW_H_INCLUDE
